TypeScript, Less, Fetching, Post
ss-react-group/JustAnotherTwitter pull request #1
Opened 2018-08-27 14:20 UTC by Kamieniu

Simple project, ready to use.
Implemented TypeScript and Less.

Also created prototype for handling fetch request.

2018-08-27 14:22 UTC, fstodulski commented on src/App.tsx
> +
Need some comment

2018-08-27 14:23 UTC, fstodulski commented on src/App.tsx
> +  public componentDidMount() {}
Unused method

2018-08-27 18:39 UTC, stanimirtt commented on config/webpack.config.dev.js
> +    extensions: [
We may need only - js, jsx, ts, tsx, less for resolving.

2018-08-27 18:40 UTC, stanimirtt commented on config/webpack.config.dev.js
> +      'react-native': 'react-native-web',
Do we need that?

2018-08-27 18:40 UTC, stanimirtt commented on config/webpack.config.dev.js
> +};
Add new line here.

2018-08-27 18:41 UTC, dpyskunova approved these changes

2018-08-27 18:41 UTC, stanimirtt commented on tsconfig.prod.json
> +}
new line

2018-08-27 18:41 UTC, stanimirtt commented on tslint.json
> +}
new line

2018-08-27 18:43 UTC, stanimirtt requested changes
Please look at my comments. Rename post.tsx to Post.tsx.

2018-08-28 08:58 UTC, suezzo approved these changes

2018-08-30 10:08 UTC, dpyskunova approved these changes

2018-09-10 09:00 UTC, stanimirtt approved these changes

2018-09-10 09:01 UTC, merged