WIP: Initial commit for authorization page.
ss-react-group/JustAnotherTwitter pull request #6
Opened 2018-09-13 08:58 UTC by dpyskunova

Need to add stores, password popup, log out.

2018-09-13 09:13 UTC, stanimirtt commented on src/pages/Authorization/index.tsx
> +import Authorization from './Authorization';
Update according the Michal changes.

2018-09-13 09:13 UTC, stanimirtt commented on src/pages/Authorization/Authorization.tsx
> +
Remove the new line.

2018-09-13 09:14 UTC, stanimirtt commented on src/env/envitonment.tsx
> +  api: 'http://localhost:9081/'
Do not change this.

2018-09-13 09:14 UTC, stanimirtt commented on src/components/Slogan/index.tsx
> +import Slogan from './Slogan';
Same here.

2018-09-13 09:14 UTC, stanimirtt commented on src/components/Slogan/Slogan.tsx
> +class Slogan extends React.Component {
Put here export.

2018-09-13 09:30 UTC, dpyskunova commented on src/components/Common/Inputs/PasswordEncrypting/PasswordEncrypting.tsx
> +import { encrypt } from '../../../../helpers/UsefulFunctions';
change the name "UsefulFunctions"

2018-09-14 08:17 UTC, Kamieniu commented on package.json
> +    "history": "^4.7.2",
Do we really need new package? 
React Router is mostly a wrapper around the history library. history handles interaction with the browser's window.history for you with its browser and hash histories.
https://stackoverflow.com/questions/31079081/programmatically-navigate-using-react-router

2018-09-14 08:19 UTC, Kamieniu commented on src/App.tsx
> +    this.props.stores.userDetailsStore.user = JSON.parse(localStorage.getItem('userDetails'));
to keep it more readable :
const userDetails = JSON.parse(localStorage.getItem('userDetails'));
this.props.stores.userDetailsStore.user = userDetails

2018-09-14 08:50 UTC, fstodulski requested changes
Check my comments

2018-09-14 08:50 UTC, Kamieniu commented on src/components/Common/Button/FbLoginButton/FbLoginButton.tsx
> +    const authorizeUser = auth(userDetails);
We already have Fetch abstract class to handle all request. Try use it to Inherit your auth function

2018-09-14 08:50 UTC, Kamieniu commented on src/components/Common/FbRegisterButton/FbRegisterButton.tsx
> +    const authorizeUser = auth(userDetails);
Here. Try the same. Inherit Fetch abstract class.

2018-09-14 08:50 UTC, Kamieniu commented on src/components/Login/Login.tsx
> +            <input name="email" placeholder="john@doe.com" autoFocus type="email" value={email} onChange={this.onChange}/>
You will use here DefaultInput component here, later.

2018-09-14 08:50 UTC, Kamieniu commented on src/components/Register/Register.tsx
> +
Use Fetch abstract class to inherit functionality.

2018-09-14 08:50 UTC, Kamieniu commented on src/components/Slogan/Slogan.tsx
> +export class Slogan extends React.Component {
Also, this could be a "STUPID" component. We don't need to hold slogan in state.

2018-09-14 08:50 UTC, Kamieniu commented on src/helpers/db.tsx
> +
Here, use Fetch abstract class

2018-09-14 08:50 UTC, Kamieniu commented on src/index.scss
> +@font-face {
Probably, we need to create an file inside /assets/typography.scss and import it inside index.ts

2018-09-14 08:50 UTC, Kamieniu commented on src/pages/Authorization/Authorization.scss
> +body, html {
Body html exist already in App component.

2018-09-14 08:50 UTC, Kamieniu commented on src/pages/Authorization/Authorization.scss
> +*, *:before, *:after {
Also, we will probably use normalize.css for it.

2018-09-14 08:50 UTC, Kamieniu commented on src/pages/Authorization/Authorization.scss
> +    background-color: var(--blue);
use scss $blue variable instead
all variables comes from assets/styles/variables

2018-09-14 09:19 UTC, stodorov-ss commented on src/App.tsx
> +interface IAppState {}
You do not need that empty interface.
just pash void instead it.

2018-09-14 09:20 UTC, stodorov-ss commented on src/App.tsx
> +    this.props.stores.userDetailsStore.user = JSON.parse(localStorage.getItem('userDetails'));
userDetailsStore -> userDetails

2018-09-14 09:22 UTC, stodorov-ss commented on src/components/Common/Button/FbLoginButton/FbLoginButton.tsx
> +import {auth} from '../../../../helpers/db';
{auth} -> { auth }

2018-09-14 09:23 UTC, stodorov-ss commented on src/components/Common/FbRegisterButton/FbRegisterButton.tsx
> +class Register extends Component<IFacebookLoginProps, IFacebookLoginState> {
just past void, void.

2018-09-14 09:24 UTC, stodorov-ss commented on src/components/Common/FbRegisterButton/FbRegisterButton.tsx
> +  handleFacebookResponse = (response: any): void => {
Why are you using store?

2018-09-14 10:57 UTC, Kamieniu commented on src/components/Common/FbRegisterButton/FbRegisterButton.tsx
> +  handleFacebookResponse = (response: any): void => {
Also, we know how response from FB looks like. We can create an interface for it.

2018-09-17 08:40 UTC, stanimirtt approved these changes

2018-09-17 09:03 UTC, fstodulski approved these changes

2018-09-17 09:03 UTC, fstodulski commented on src/helpers/db.tsx
> +  return fetch(
Here, use Fetch abstract class

2018-09-17 09:12 UTC, merged